language: node_js

node_js:
  - "4.1"
  - "4.0"
  - "0.12"

services:
  - mongodb

before_script:
  - npm install -g mocha

script:
  - mocha

deploy:
  provider: heroku
  api_key:
    secure:
  app:
  on:
    branch: master
    node: '0.12'
